[package]
name = "branp-cli"
version = "0.1.0"
description = "A blazingly fast, general use CLI tool."
license = "MIT"
readme = "README.md"
authors = ["Brandon Pacewic <pacewicbrandon@gmail.com>"]
edition = "2021"

[[bin]]
name = "bp"
path = "src/main.rs"

[lib]
name = "branp_cli"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
clap_complete = { version = "4.5.56", features = ["unstable-dynamic"] }
color-print = "0.3.7"
memchr = "2.7.4"
reqwest = { version = "0.13.4", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml_edit = "0.25.10"

[workspace]
members = ["benches/benchsuite"]
resolver = "2"
